version: '3'

services:
  app:
    build: ../../../..
    container_name: app # Имя контейнера
    depends_on:
      - postgres # Ожидаем, пока контейнер postgres стартует
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "3000:3000"

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432' # Маппинг порта хоста на порт контейнера
