version: '3' # Версия Compose

services:
  app:
    build: . # Собираем образ из текущей директории Dockerfile
    container_name: app # Имя контейнера
    depends_on:
      - postgres # Ожидаем, пока контейнер postgres стартует
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mydatabase # Изменено на имя контейнера postgres
      - SPRING_DATASOURCE_USERNAME=myuser # Удалены лишние кавычки
      - SPRING_DATASOURCE_PASSWORD=secret # Удалены лишние кавычки

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432' # Маппинг порта хоста на порт контейнера
